apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cosigned
resources:
- ../../cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cosigned
- ../../cluster-scope/base/rbac.authorization.k8s.io/clusterroles/cosigned
- configmap.yaml
- deployment.yaml
- ../../cluster-scope/base/cosigned
- publicsecret.yaml
- rolebinding.yaml
- role.yaml
- secret.yaml
- serviceaccount.yaml
- service.yaml