---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cosigned-webhook
  labels:
    helm.sh/chart: cosigned-v0.1.9
    app.kubernetes.io/name: cosigned
    app.kubernetes.io/instance: cosigned
    app.kubernetes.io/version: "v1.4.1"
    app.kubernetes.io/managed-by: Helm
    control-plane: cosigned-webhook
rules:
  # Needed to watch and load configuration and secret data.
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "update", "watch"]

  # Needed for leader election
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
